[tools]
ast-grep = "0.39.7"
cargo-binstall = "1.15.10"
"cargo:bob-nvim" = "4.1.4"
"cargo:eza" = "0.23.4"
"cargo:fnm" = "1.38.1"
"cargo:ripgrep" = "15.1.0"
"cargo:zellij" = "0.43.1"
"cargo:zoxide" = "0.9.8"
dotnet = "9.0.306"
fd = "10.3.0"
fzf = "0.66.1"
ghcup = "0.1.50.2"
go = "1.25.3"
"go:github.com/docker/docker-language-server/cmd/docker-language-server" = "0.20.1"
java = "25.0.1"
jq = "1.8.1"
maven = "3.9.11"
"npm:pnpm" = "10.20.0"
pipx = "1.8.0"
"pipx:virtualfish" = "2.5.9"
poetry = "2.2.1"
rust = "1.91.0"
shfmt = "3.12.0"
starship = "1.24.0"
usage = "2.6.0"
zig = "0.15.2"
zoxide = "0.9.8"
uv = "0.9.7"
dart = "3.9.4"
flutter = "3.35.7-stable"
"npm:@anthropic-ai/claude-code" = "2.0.32"
lazygit = "0.55.1"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]

[settings.npm]
bun = true
