[tools]
ast-grep = "0.40.5"
cargo-binstall = "1.17.4"
"cargo:bob-nvim" = "4.1.6"
"cargo:eza" = "0.23.4"
"cargo:ripgrep" = "15.1.0"
"cargo:zellij" = "0.43.1"
"cargo:zoxide" = "0.9.8"
rust = "1.91.1"
dotnet = "9.0.306"
fd = "10.3.0"
fzf = "0.67.0"
ghcup = "0.1.50.2"
go = "1.25.4"
java = "25.0.1"
jq = "1.8.1"
maven = "3.9.11"
# "npm:pnpm" = "10.22.0"
pipx = "1.8.0"
"pipx:virtualfish" = "2.5.9"
poetry = "2.2.1"

shfmt = "3.12.0"
starship = "1.24.1"
usage = "2.8.0"
zig = "0.15.2"
zoxide = "0.9.8"
uv = "0.9.10"
dart = "3.10.0"
"npm:@anthropic-ai/claude-code" = "2.1.25"
node = "24.11.0"
"go:github.com/jesseduffield/lazygit" = "latest"
pnpm = "latest"
bun = "latest"
yazi = "latest"
"cargo:alacritty" = "latest"
"cargo:neovide" = "latest"
[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true

[settings.npm]
bun = true
